apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  annotations:
    argocd/app-name: test-dev
    backstage.io/kubernetes-id: test
    backstage.io/kubernetes-namespace: test-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: LiorJanus/test
    quay.io/repository-slug: "/test"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/test?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/test?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/test"
  providesApis:
    - "test"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "test"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/test"
  definition:
    $text: ./openapi.yaml
